# Generated by Django 5.1.2 on 2024-11-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_myuser_user_alter_myuser_otp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="otp_create_time",
            new_name="otp_created_at",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
