# Generated by Django 5.1.2 on 2024-11-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_otp_create_time_myuser_otp_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="otp_created_at",
            new_name="otp_create_time",
        ),
    ]
