# Generated by Django 5.1.2 on 2024-11-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_otp_created_at_myuser_otp_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="business_license",
            field=models.FileField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AddField(
            model_name="seller",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
