# Generated by Django 5.1.2 on 2024-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_icon_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="brand_images/"),
        ),
    ]
