# Generated by Django 5.1.2 on 2024-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_brand_image_category_icon_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
