# Generated by Django 5.1.2 on 2024-11-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_images/"
            ),
        ),
    ]
